### ISSUE TITLE
Error when listening to realtime events

### ISSUE THREAD

**Issue by gcostaapps** [supabase-community/supabase-flutter#81]
# Bug report

## Describe the bug

Sometimes when I'm subscribed to a table in my database and reveive new events I got this error, but couldn't find the reason to it. Any tips where to search?

```
E/flutter ( 4940): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Concurrent modification during iteration: Instance(length:18) of '_GrowableList'.
E/flutter ( 4940): #0      ListIterator.moveNext (dart:_internal/iterable.dart:336:7)
E/flutter ( 4940): supabase/supabase-flutter#1      WhereIterator.moveNext (dart:_internal/iterable.dart:438:22)
E/flutter ( 4940): supabase/supabase-flutter#2      Iterable.forEach (dart:core/iterable.dart:279:23)
E/flutter ( 4940): supabase/supabase-flutter#3      RealtimeClient.onConnMessage.<anonymous closure> (package:realtime_client/src/realtime_client.dart:264:60)
E/flutter ( 4940): supabase/supabase-flutter#4      new RealtimeClient.<anonymous closure> (package:realtime_client/src/realtime_client.dart:86:21)
E/flutter ( 4940): supabase/supabase-flutter#5      RealtimeClient.onConnMessage (package:realtime_client/src/realtime_client.dart:249:11)
E/flutter ( 4940): supabase/supabase-flutter#6      RealtimeClient.connect.<anonymous closure> (package:realtime_client/src/realtime_client.dart:108:11)
E/flutter ( 4940): supabase/supabase-flutter#7      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 4940): supabase/supabase-flutter#8      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 4940): supabase/supabase-flutter#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 4940): supabase/supabase-flutter#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 4940): supabase/supabase-flutter#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4940): supabase/supabase-flutter#12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter ( 4940): supabase/supabase-flutter#13     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
E/flutter ( 4940): supabase/supabase-flutter#14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 4940): supabase/supabase-flutter#15     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 4940): supabase/supabase-flutter#16     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 4940): supabase/supabase-flutter#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 4940): supabase/supabase-flutter#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 4940): supabase/supabase-flutter#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4940): supabase/supabase-flutter#20     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter ( 4940): supabase/supabase-flutter#21     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter ( 4940): supabase/supabase-flutter#22     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 4940): supabase/supabase-flutter#23     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 4940): supabase/supabase-flutter#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 4940): supabase/supabase-flutter#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 4940): supabase/supabase-flutter#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4940): supabase/supabase-flutter#27     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter ( 4940): supabase/supabase-flutter#28     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter ( 4940): supabase/supabase-flutter#29     _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter ( 4940): supabase/supabase-flutter#30     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1150:21)
E/flutter ( 4940): supabase/supabase-flutter#31     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 4940): supabase/supabase-flutter#32     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 4940): supabase/supabase-flutter#33     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 4940): supabase/supabase-flutter#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 4940): supabase/supabase-flutter#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4940): supabase/supabase-flutter#36     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
E/flutter ( 4940): supabase/storage-dart#16     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
E/flutter ( 4940): supabase/supabase-flutter#38     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
E/flutter ( 4940): supabase/supabase-flutter#39     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
E/flutter ( 4940): supabase/supabase-flutter#40     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
E/flutter ( 4940): supabase/supabase-flutter#41     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 4940): supabase/supabase-flutter#42     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 4940): supabase/supabase-flutter#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 4940): supabase/supabase-flutter#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 4940): supabase/supabase-flutter#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4940): supabase/supabase-flutter#46     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter ( 4940): supabase/supabase-flutter#47     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter ( 4940): supabase/supabase-flutter#48     _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter ( 4940): supabase/supabase-flutter#49     _Socket._onData (dart:io-patch/socket_patch.dart:2166:41)
E/flutter ( 4940): supabase/supabase-dart#64     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 4940): supabase/supabase-flutter#51     _CustomZone.runUnary (dart:async/zone.d
```

Running the last version of supabase_flutter

**Comment by alig1882** [comment]
Just to chime in and add some urgency, I am also getting the same problem.

**Comment by imcouri** [comment]
same here

**Comment by dshukertjr** [comment]
Sorry for taking so much time. I have found the cause of this bug. Working on a fix now!
