### ISSUE TITLE
Error watching table on web

### ISSUE THREAD

**Issue by gcostaapps** [supabase-community/supabase-flutter#88]
Hi, I'm running the same code on a tablet and on the web, on the web when I make changes in an array of int fields inside a table that is being watched I got an error from the realtime_client. Coudn't find why, this error was not happening before, the users start to complain about it this week.

```
_subscription = _client
            .from('liveLesson:id=eq.${r.id}')
            .on(SupabaseEventTypes.all, (payload) => watchLiveLesson(payload))
            .subscribe();
```

Error
```
Error: Expected a value of type 'String?', but got one of type '_JsonMap'
    at Object.throw_ [as throw] (http://localhost:52483/dart_sdk.js:5067:11)
    at Object.castError (http://localhost:52483/dart_sdk.js:5026:15)
    at Object.cast [as as] (http://localhost:52483/dart_sdk.js:5351:17)
    at dart.NullableType.new.as (http://localhost:52483/dart_sdk.js:6911:60)
    at realtime_subscription.Binding.new.<anonymous> (http://localhost:52483/packages/realtime_client/src/push.dart.lib.js:430:37)
    at realtime_subscription.RealtimeSubscription.new.trigger (http://localhost:52483/packages/realtime_client/src/push.dart.lib.js:521:12)
    at http://localhost:52483/packages/realtime_client/src/push.dart.lib.js:967:145
    at WhereIterable.new.forEach (http://localhost:52483/dart_sdk.js:22295:11)
    at http://localhost:52483/packages/realtime_client/src/push.dart.lib.js:967:117
    at realtime_client.RealtimeClient.new.<anonymous> (http://localhost:52483/packages/realtime_client/src/push.dart.lib.js:1101:81)
    at realtime_client.RealtimeClient.new.onConnMessage (http://localhost:52483/packages/realtime_client/src/push.dart.lib.js:972:12)
    at http://localhost:52483/packages/realtime_client/src/push.dart.lib.js:831:16
    at _RootZone.runUnaryGuarded (http://localhost:52483/dart_sdk.js:40378:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:52483/dart_sdk.js:33906:22)
    at _ControllerSubscription.new.[_add] (http://localhost:52483/dart_sdk.js:33855:26)
    at _SyncStreamController.new.[_sendData] (http://localhost:52483/dart_sdk.js:36868:34)
    at _SyncStreamController.new.[_sendData] (http://localhost:52483/dart_sdk.js:36978:32)
    at _SyncStreamController.new.[_add] (http://localhost:52483/dart_sdk.js:36681:26)
    at _SyncStreamController.new.add (http://localhost:52483/dart_sdk.js:36648:19)
    at _RootZone.runUnaryGuarded (http://localhost:52483/dart_sdk.js:40378:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:52483/dart_sdk.js:33906:22)
    at _ControllerSubscription.new.[_add] (http://localhost:52483/dart_sdk.js:33855:26)
    at _SyncStreamController.new.[_sendData] (http://localhost:52483/dart_sdk.js:36868:34)
    at _SyncStreamController.new.[_sendData] (http://localhost:52483/dart_sdk.js:36978:32)
    at _SyncStreamController.new.[_add] (http://localhost:52483/dart_sdk.js:36681:26)
    at _SyncStreamController.new.add (http://localhost:52483/dart_sdk.js:36648:19)
    at _StreamSinkWrapper.new.add (http://localhost:52483/dart_sdk.js:37015:24)
    at _GuaranteeSink.new.add (http://localhost:52483/packages/stream_channel/src/stream_channel_controller.dart.lib.js:1179:24)
    at http://localhost:52483/packages/web_socket_channel/src/copy/web_socket_impl.dart.lib.js:1470:37
    at Object._checkAndCall (http://localhost:52483/dart_sdk.js:5274:16)
    at Object.dcall (http://localhost:52483/dart_sdk.js:5279:17)
    at WebSocket.<anonymous> (http://localhost:52483/dart_sdk.js:109327:100)
```

Using flutter version stable 2.10.1 and supabase: ^0.2.15
(Was using supabase 0.2.13 before but with the same error, tried to update but the error persist)

**Comment by gcostaapps** [comment]
Is there any workaround or estimated date to fix this bug? I can't use realtime on the web with this, it affects a large portion of my usecases.

**Comment by dshukertjr** [comment]
@gcostaapps Thank you so much for your patients. Let me tackle this issue over the weekend.

**Comment by gcostaapps** [comment]
Hi @dshukertjr , I don't know if you have changed something but I've updated the version of the library to the latest and now I think the error is gone.

**Comment by dshukertjr** [comment]
@gcostaapps I'm glad to hear that! We did push an auth update, but not sure if that did the trick. Please do let us know if it happens again though.
